# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12image_server.proto\x12\x0cimage_server\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x1e\n\rImageResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x32\xf6\x01\n\tProcessor\x12O\n\x0eGrayscaleImage\x12\x1a.image_server.ImageRequest\x1a\x1b.image_server.ImageResponse\"\x00(\x01\x30\x01\x12L\n\x0bInvertImage\x12\x1a.image_server.ImageRequest\x1a\x1b.image_server.ImageResponse\"\x00(\x01\x30\x01\x12J\n\tIconImage\x12\x1a.image_server.ImageRequest\x1a\x1b.image_server.ImageResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=36
  _globals['_IMAGEREQUEST']._serialized_end=65
  _globals['_IMAGERESPONSE']._serialized_start=67
  _globals['_IMAGERESPONSE']._serialized_end=97
  _globals['_PROCESSOR']._serialized_start=100
  _globals['_PROCESSOR']._serialized_end=346
# @@protoc_insertion_point(module_scope)
